# Generated by Django 4.1 on 2022-09-17 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0003_cate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cate',
        ),
    ]
