# Generated by Django 4.1 on 2022-09-18 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0004_delete_cate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comment',
        ),
    ]
